/*
 * NewJPanel.java
 *
 * Created on 22 de diciembre de 2005, 10:52 PM
 */

package gui;

/**
 *
 * @author  xpJP
 */
public class NewJPanel extends javax.swing.JPanel {
    
    /** Creates new form NewJPanel */
    public NewJPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jFrame1 = new javax.swing.JFrame();
        jList1 = new javax.swing.JList();
        jTextArea1 = new javax.swing.JTextArea();
        jList2 = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        add(jList1, java.awt.BorderLayout.NORTH);

        add(jTextArea1, java.awt.BorderLayout.EAST);

        add(jList2, java.awt.BorderLayout.WEST);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
